---
output:
  html_document:
    df_print: paged
    toc: true
    number_sections: false
    toc_depth: 4
    toc_float:
      collapsed: false
      smooth_scroll: false
params:
  rwd: rwd
  trait.blurb: trait.blurb
  trait.name: trait.name
  trait.code: trait.code
  load.summary: load.summary
  aaos.summary: aaos.summary
  ab42.summary: ab42.summary
  ptau.summary: ptau.summary
  tau.summary: tau.summary
  hipv.summary: hipv.summary
  trait.summary: trait.summary
  load.clump: load.clump
  aaos.clump: aaos.clump
  ab42.clump: ab42.clump
  ptau.clump: ptau.clump
  tau.clump: tau.clump
  hipv.clump: hipv.clump
  out.path: out.path
  trait_load.path: trait_load.path
  trait_aaos.path: trait_aaos.path
  trait_ab42.path: trait_ab42.path
  trait_ptau.path: trait_ptau.path
  trait_tau.path: trait_tau.path
  trait_hipv.path: trait_hipv.path
  p.threshold: p.threshold
---

#Mendelian Randomization Analysis: Alzheimer\'s Disease and `r params$trait.name`
By Dr. Shea Andrews, generated on `r Sys.Date()`

---

```{r MasterSetup, echo=FALSE, warning =FALSE, message=FALSE}
knitr::opts_knit$set(root.dir = params$rwd)
knitr::opts_chunk$set(echo = TRUE)

ifelse(!dir.exists(paste0('../', params$out.path, params$trait.code)),
       dir.create(paste0('../', params$out.path, params$trait.code)),
       FALSE)

#knitr::opts_chunk$set(cache = params$Cache)
knitr::opts_chunk$set(cache.path = paste0('../', params$out.path, params$trait.code, '/MR_cache/'))

```

```{r DatasetCreation, child = 'bmr_dataset_creation.Rmd'}
```

```{r MRanalysis, child = 'bmr_analysis.Rmd'}
```
