---
title: "MR Results"
author: "Shea Andrews"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/sheaandrews/GitCode/MR_ADPhenome")
# setwd("/Users/sheaandrews/GitCode/MR_ADPhenome")

library(tidyverse)
library(glue)
library(TwoSampleMR)
library(gridExtra)
library(qvalue)
source('scripts/miscfunctions.R', chdir = TRUE)

DATE = Sys.Date()

MR_results.path = snakemake@input[["infile"]]
MRdat.path = snakemake@input[["infile"]]
mrpresso_global.path = snakemake@input[["infile"]]
mrpresso_global_wo_outliers.path = snakemake@input[["infile"]]
egger_comb.path = snakemake@input[["infile"]]
power.path = snakemake@input[["infile"]]
```

```{r sandbox, eval=FALSE, echo=FALSE}
model <- "MR_ADphenome"

MR_results.path = glue("results/{model}/All/MRresults.txt")
MRdat.path = glue("results/{model}/All/mrpresso_MRdat.csv")
mrpresso_global.path = glue("results/{model}/All/global_mrpresso.txt")
mrpresso_global_wo_outliers.path = glue("results/{model}/All/global_mrpresso_wo_outliers.txt")
egger_comb.path = glue("results/{model}/All/pleiotropy.txt")
power.path = glue("results/{model}/All/power.txt")

```


```{r load-data}
##  Read in R datasets
## Outcomes to include the results 

## Files
MR_results <- read_tsv(MR_results.path) 

MRdat.raw <- read_csv(MRdat.path, guess_max = 100000) 

mrpresso_global <- read_tsv(mrpresso_global.path) 

mrpresso_global_wo_outliers <- read_tsv(mrpresso_global_wo_outliers.path) 

mrpresso_global_comb <- bind_rows(mrpresso_global, mrpresso_global_wo_outliers)

egger_comb <- read_tsv(egger_comb.path) %>% 
  rename(egger_se = se) 

power <- read_tsv(power.path) %>% 
  select(exposure, outcome, pt, outliers_removed, pve.exposure, F, Power) %>% 
  mutate(pve.exposure = round(pve.exposure*100, 2), 
         F = round(F, 2), 
         Power = round(Power, 2)) 

```

## Exposures-Outcomes 
```{r}
MR_results %>% 
  filter(outliers_removed == FALSE, method == "Inverse variance weighted (fixed effects)") %>%
  group_by(exposure, pt) %>% 
  summarise(n_outcome = n_distinct(outcome), min_nsnp = min(nsnp), mean_nsnp = mean(nsnp), max_nsnp = max(nsnp)) %>% 
  mutate_at(vars("min_nsnp", "mean_nsnp", "max_nsnp"), round, 1) %>%
  pivot_wider(names_from = "pt", values_from = c("n_outcome", "min_nsnp", "mean_nsnp", "max_nsnp")) %>% 
  select(exposure, ends_with("06"), ends_with("08")) %>%
  knitr::kable(format = "html") %>% 
  kableExtra::kable_styling() %>% 
  kableExtra::add_header_above(c(" " = 1, "5e-6" = 4, "5e-8" = 4))
  
```


## Harmonized exposure-outcome SNP dataset

```{r merge-data, echo=FALSE}
MRdat <- MRdat.raw  %>% 
  ## Merge Sample Size information
  select(-samplesize.outcome, -samplesize.exposure) %>% 
  left_join(select(samplesize, -pmid), by = c('exposure' = 'code')) %>% 
  rename(samplesize.exposure = samplesize, 
         ncase.exposure = ncase, 
         ncontrol.exposure = ncontrol, 
         logistic.exposure = logistic, 
         exposure.name = trait, 
         domain.exposure = domain) %>% 
  left_join(select(samplesize, -pmid), by = c('outcome' = 'code')) %>% 
  rename(samplesize.outcome = samplesize, 
         ncase.outcome = ncase, 
         ncontrol.outcome = ncontrol, 
         logistic.outcome = logistic, 
         outcome.name = trait, 
         domain.outcome = domain) 

```

## MR Resuts 

```{r}
MRsummary <- MR_results %>% 
  mutate(method = str_replace(method, "Inverse variance weighted \\(fixed effects\\)", 'IVW'), 
         method = str_replace(method, "MR Egger", 'Egger'), 
         method = str_replace(method, "Weighted median", 'WME'), 
         method = str_replace(method, "Weighted mode", 'WMBE')) %>%
  rename(MR.pval = pval) %>%
  ## Join MR-PRESSO Global results
  left_join(select(mrpresso_global_comb, outcome, exposure, pt, RSSobs, pval, outliers_removed), 
            by = c('outcome', 'exposure', 'pt', 'outliers_removed')) %>% 
  rename(MRPRESSO.pval = pval) %>% 
  ## Join Egger Intercept results
  left_join(select(egger_comb, outcome, exposure, pt, egger_intercept, egger_se, pval, outliers_removed), 
            by = c('outcome', 'exposure', 'pt', 'outliers_removed')) %>% 
  rename(Egger.pval = pval) %>% 
  select(outcome, exposure, pt, method, outliers_removed, nsnp, n_outliers, b, se, MR.pval, 
         RSSobs, MRPRESSO.pval, egger_intercept, egger_se, Egger.pval) %>% 
  arrange(outcome, exposure, pt, method, outliers_removed) %>% 
  ## Merge Sample Size information
  left_join(select(samplesize, code, trait, domain), by = c('exposure' = 'code')) %>% 
  rename(exposure.name = trait, 
         exposure.domain = domain) %>% 
  left_join(select(samplesize, code, trait, domain), by = c('outcome' = 'code')) %>% 
  rename(outcome.name = trait, 
         outcome.domain = domain) 

## Spread by methods
mrresults.methods <- MRsummary %>% 
  mutate(b = signif(b, 2), 
         se = signif(se, 2), 
         MR.pval = signif(MR.pval, 2), 
         RSSobs = round(RSSobs, 1), 
         egger_intercept = signif(egger_intercept, 3), 
         egger_se = signif(egger_se, 2), 
         Egger.pval = signif(Egger.pval, 2)) %>%
  pivot_wider(names_from = method, names_glue = "{method}_{.value}", values_from = c(b, se, MR.pval)) %>%
 # myspread(method, c(b, se, MR.pval)) %>% 
  mutate(IVW_Signif = as.character(signif.num(IVW_MR.pval)), 
         Egger_Signif = as.character(signif.num(Egger_MR.pval)),
         WME_Signif = as.character(signif.num(WME_MR.pval)), 
         WMBE_Signif = as.character(signif.num(WMBE_MR.pval))) 

## Spread by outlier removal MR-PRESSO
mrresults.methods_presso <- mrresults.methods %>% 
  left_join(power) %>% 
  myspread(outliers_removed, 
           c(nsnp, n_outliers, pve.exposure, F, Power, RSSobs, MRPRESSO.pval, egger_intercept, 
             egger_se, Egger.pval, IVW_b, IVW_MR.pval, IVW_se, Egger_b, Egger_MR.pval, 
             Egger_se, WME_b, WME_MR.pval, WME_se, 
             WMBE_b, WMBE_MR.pval, WMBE_se, IVW_Signif, 
             Egger_Signif, WME_Signif, WMBE_Signif)) %>% 
  arrange(pt, outcome, exposure) %>%
  arrange(outcome.name, exposure.name, pt) %>% 
  select(outcome, exposure, outcome.name, exposure.name, pt, FALSE_nsnp, FALSE_pve.exposure, FALSE_F, FALSE_n_outliers,
         FALSE_IVW_b, FALSE_IVW_se, FALSE_IVW_MR.pval, FALSE_IVW_Signif, FALSE_Power,
         FALSE_Egger_b, FALSE_Egger_se, FALSE_Egger_MR.pval, FALSE_Egger_Signif,  
         FALSE_WME_b, FALSE_WME_se, FALSE_WME_MR.pval, FALSE_WME_Signif, 
         FALSE_WMBE_b, FALSE_WMBE_se, FALSE_WMBE_MR.pval, FALSE_WMBE_Signif, 
         FALSE_RSSobs, FALSE_MRPRESSO.pval, FALSE_egger_intercept, FALSE_egger_se, FALSE_Egger.pval, 
         TRUE_IVW_b, TRUE_IVW_se, TRUE_IVW_MR.pval, TRUE_IVW_Signif, TRUE_Power,
         TRUE_Egger_b, TRUE_Egger_se, TRUE_Egger_MR.pval, TRUE_Egger_Signif, 
         TRUE_WME_b, TRUE_WME_se, TRUE_WME_MR.pval, TRUE_WME_Signif, 
         TRUE_WMBE_b, TRUE_WMBE_se, TRUE_WMBE_MR.pval, TRUE_WMBE_Signif,
         TRUE_RSSobs, TRUE_MRPRESSO.pval, TRUE_egger_intercept, TRUE_egger_se, TRUE_Egger.pval) %>% 
         magrittr::set_colnames(colnames(.) %>% str_replace(., "FALSE_", "") %>% str_replace(., "TRUE_", "outlier_"))


  

```


```{r print-res, knitr.kable.NA = ''}

mrresults.methods_presso %>%
  select(-outcome, -exposure, -ends_with("Signif")) %>% 
  mutate(pt = as.character(pt)) %>%
  knitr::kable(format = "html") %>% 
  kableExtra::kable_styling() %>% 
  kableExtra::add_header_above(c(" " = 7, "IVW" = 4, "MR Egger" = 3, "WME" = 3, "WBE" = 3, " " = 5,  "IVW" = 4, "MR Egger" = 3, "WME" = 3, "WBE" = 3, " " = 5))

```


## Best results 

```{r}
## -------------------------------------------------------------------------------- ##
##                      Filter results for MR-PRESSO and best PT                    ## 
mr_res <- MRsummary %>% 
  filter(method == 'IVW') %>% 
  group_by(outcome, exposure) %>% 
  filter(outliers_removed == ifelse(TRUE %in% outliers_removed, TRUE, FALSE)) %>% 
  ungroup()

## Generate FDR values
qobj <- qvalue(p = mr_res$MR.pval, fdr.level = 0.1)
qvales.df <- tibble(pvalues = qobj$pvalues, lfdr = qobj$lfdr, 
                    qval = qobj$qvalues, significant = qobj$significant)

mr_best <- mr_res %>% 
  bind_cols(select(qvales.df, qval)) %>% 
  group_by(outcome, exposure) %>% 
  arrange(MR.pval) %>% 
  slice(1) %>% 
  ungroup() %>% 
  select(outcome, exposure, pt, outliers_removed, qval) %>%
  left_join(mrresults.methods, by = c('outcome', 'exposure', 'pt', 'outliers_removed')) %>% 
  mutate(MRPRESSO.pval_rm = as.numeric(str_replace(MRPRESSO.pval, '<', ""))) %>% 
  mutate(pass = ifelse(qval > 0.05, FALSE,
                       ifelse(MRPRESSO.pval_rm > 0.05 & Egger.pval > 0.05, TRUE,
                              ifelse(Egger_MR.pval < 0.05 | WME_MR.pval < 0.05 | WMBE_MR.pval < 0.05, TRUE, FALSE))))  %>% 
  split(., 1:nrow(.)) %>% 
  map_dfr(., function(x){
    x %>% 
      mutate(pass = ifelse(pass == FALSE, FALSE, passfunc(IVW_MR.pval, IVW_b, 
                                                          Egger_MR.pval, Egger_b, 
                                                          WME_MR.pval, WME_b, 
                                                          WMBE_MR.pval, WMBE_b)))
  }) %>% 
  mutate(pass_0.1 = ifelse(qval > 0.1 | qval < 0.05, FALSE,
                           ifelse(MRPRESSO.pval > 0.05 & Egger.pval > 0.05, TRUE,
                                  ifelse(Egger_MR.pval < 0.05 | WME_MR.pval < 0.05 | WMBE_MR.pval < 0.05, TRUE, FALSE)))) %>% 
  split(., 1:nrow(.)) %>% 
  map_dfr(., function(x){
    x %>% 
      mutate(pass_0.1 = ifelse(pass_0.1 == FALSE, FALSE, passfunc(IVW_MR.pval, IVW_b, 
                                                                  Egger_MR.pval, Egger_b, 
                                                                  WME_MR.pval, WME_b, 
                                                                  WMBE_MR.pval, WMBE_b)))
  }) %>%
  left_join(select(samplesize, code, domain), by = c("exposure" = "code")) %>% 
  left_join(select(samplesize, code, domain), by = c("outcome" = "code")) %>% 
  rename(domain.exposure = domain.x, domain.outcome = domain.y) %>% 
  mutate(domain.outcome = fct_relevel(domain.outcome, "Psychosocial", "Health", "Lifestyle"),
         domain.exposure = fct_relevel(domain.exposure, "Diagnosis", "CSF", "Neuropathology", "Neuroimaging"))

```


```{r}
out.final <- mr_best %>% 
  mutate(IVW = paste0(IVW_b, '\n(',IVW_se, ')')) %>% 
  mutate(`MR-Egger` = paste0(Egger_b, '\n(', Egger_se, ')', Egger_Signif)) %>% 
  mutate(`Weighted median` = paste0(WME_b, '\n(',WME_se, ')', WME_Signif)) %>%
  mutate(`Weighted mode` = paste0(WMBE_b, '\n(',WMBE_se, ')', WMBE_Signif)) %>%
  select(outcome, exposure, outcome.name, exposure.name, pt, nsnp, n_outliers, IVW, qval, 
         `MR-Egger`, `Weighted median`, `Weighted mode`, MRPRESSO.pval, Egger.pval, pass, 
         -domain.exposure, -domain.outcome) %>% 
  mutate(Egger.pval = round_sci(Egger.pval)) %>%
  mutate(qval = round_sci(qval)) %>%
  arrange(outcome.name, exposure.name) %>% 
  mutate(nsnp = nsnp + n_outliers) %>% 
  filter(as.numeric(qval) < 0.1) %>% 
  arrange(outcome.name, exposure.name)

```


## Heatmap 

```{r}

## Dataframe for ploting 
dat.plot <- mr_best %>%
  mutate(q_signif = as.character(signif.num(qval))) %>%
  mutate(z = IVW_b/IVW_se) %>% 
  mutate(out = ifelse(qval < 0.1, paste0(round(IVW_b, 3), '\n', '(', round_sci(qval), ')'), " ")) %>% 
  select(outcome, exposure, exposure.name, outcome.name, domain.exposure, domain.outcome, z, q_signif, out, pass, pass_0.1) %>% 
  arrange(domain.exposure, desc(domain.outcome), outcome.name, exposure.name) %>%
  mutate(outcome.name = fct_inorder(outcome.name)) %>% 
  mutate(exposure.name = fct_inorder(exposure.name)) %>% 
  group_by(domain.exposure, domain.outcome) %>%
  arrange(exposure, outcome) %>%
  mutate(outcome.name = fct_inorder(fct_drop(outcome.name))) %>% 
  mutate(exposure.name = fct_inorder(fct_drop(exposure.name))) %>% 
  mutate(outcome1 = as.integer(fct_inorder(fct_drop(outcome.name)))) %>% 
  mutate(exposure1 = as.integer(fct_inorder(fct_drop(exposure.name)))) %>% 
  ungroup()
```

```{r}
p1 <- ggplot(dat.plot) + 
  geom_raster(aes(x = exposure.name, y = outcome.name, fill = z)) + 
  facet_grid(domain.outcome ~ domain.exposure, scales = "free", space = "free", switch = "y") + 
  geom_text(data = dat.plot, size = 4, aes(label = q_signif, x = exposure.name, y = outcome.name)) +
  scale_fill_gradient2(low="steelblue", high="firebrick", mid = "white", na.value = "grey50") + 
#  coord_fixed() + 
  theme_classic() +
  geom_vline(xintercept=seq(0.5, 23.5, 1),color="white") +
  geom_hline(yintercept=seq(0.5, 11.5, 1),color="white") +
  geom_rect(data=filter(dat.plot, pass_0.1 == TRUE), size=0.5, fill=NA, colour="orange",
            aes(xmin=exposure1 - 0.5, xmax=exposure1 + 0.5, ymin=outcome1 - 0.5, ymax=outcome1 + 0.5)) + 
  geom_rect(data = filter(dat.plot, pass == TRUE), size=0.5, fill=NA, colour="red",
            aes(xmin=exposure1 - 0.5, xmax=exposure1 + 0.5, 
                ymin=outcome1 - 0.5, ymax=outcome1 + 0.5)) +
  theme(legend.position = 'right', legend.key.height = unit(2, "line"), 
        axis.text.x = element_text(angle = 35, hjust = 0), aspect.ratio=1,
        legend.title = element_blank(), legend.text = element_text(hjust = 1.5), text = element_text(size=10), 
        axis.title.x = element_blank(), axis.title.y = element_blank()) +
  scale_x_discrete(position = "top") 
p1

if(model == "MR_ADbidir"){
  ggsave(glue("results/{model}/All/{model}_heatmap{DATE}.png"), plot = p1, width = 7, height = 11, units = "in")  
} else if(model == "MR_ADphenome"){
  ggsave(glue("results/{model}/All/{model}_heatmap{DATE}.png"), plot = p1, width = 11, height = 7, units = "in")  
}


```








































